run_id = "deepseek-v3-dense-250m-1b"
run_state = "WaitingForMembers"

[config]
warmup_time = 15
cooldown_time = 5
epoch_time = 120
max_round_train_time = 60
round_witness_time = 5
min_clients = 1
init_min_clients = 1

# 62,500 * 32 * 512 = 1,024,000,000 tokens
global_batch_size_start = 32
global_batch_size_end = 32
global_batch_size_warmup_tokens = 0

verification_percent = 0
witness_nodes = 1
total_steps = 62500
waiting_for_members_extra_time = 10

[model.LLM]
architecture = "HfDeepseek"
data_type = "Pretraining"
max_seq_len = 512
cold_start_warmup_steps = 0

[model.LLM.data_location.Local]
path = "data/ultra-fineweb-deepseek-512-bin"
token_size_in_bytes = "FourBytes"
shuffle = "DontShuffle"

[model.LLM.checkpoint.Hub]
repo_id = "aethercompute/deepseek-v3-dense-250m-1b"

[model.LLM.lr_schedule.Cosine]
base_lr = 3.0e-4
warmup_steps = 1500
warmup_init_lr = 0.0
total_steps = 62500
final_lr = 3.0e-5

[model.LLM.optimizer.Distro]
clip_grad_norm = 1.0
compression_decay = 0.999
compression_chunk = 64
compression_topk = 8
quantize_1bit = true
weight_decay = 0.1
